### ISSUE TITLE
Link command fails

### ISSUE THREAD

**Issue by hupiper** [redhat-developer/vscode-openshift-tools#1266]
**Environment**
VS Code version: 1.39.2
OS: linux
Extension version: 0.1.1

**Description**
Running the Wild West demo. Created front and back, both with urls, and pushed successfully to crc. Tried link several times:

Failed to link component with error 'Error: Command failed: "/home/mdunnett/.vs-openshift/odo" link backend --project crc-demo --app demoapp --component frontend --wait --port 8080
 ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=frontend-demoapp''

Upstream issue https://github.com/openshift/odo/issues/2392

**Comment by dgolovin** [comment]
I have the same problem with wildwest example, when linking [frontend ](https://github.com/openshift-evangelists/Wild-West-Frontend) to [backend](https://github.com/openshift-evangelists/Wild-West-Backend).

**Comment by dgolovin** [comment]
Should be tested with latest released odo 1.1.1 https://github.com/openshift/odo/issues/2392#issuecomment-552735425.

**Comment by carloreggiani** [comment]
Same problem here (OpenShift 4.3): 2 error related to backend component

1. GET API error for missing rbac for fabric8, solved adding view role to system service: oc policy add-role-to-user view system:serviceaccount:<project>:default --> fixed
2. No backend service on port 8080: the Springboot application seems started ok, but nothing to browse from the backend component and following nothing to link from the frontend component (frontend is working fine!)

I tryed master and head branch from github repository.

Thanks for any help: it is a perfect tutorial to introduce OpenShift to my developers

Carlo

**Comment by dgolovin** [comment]
@carloreggiani missed your comment, sorry about that.

This issue is going to be fixed in next release.

I also have verified that wildwest application can be deployed with this extension. The only problem is running those two command mentioned in frontend readme before linking fronted to backend. 
```
$ oc policy add-role-to-user view system:serviceaccount:wildwest:default where wildwest
$ oc policy add-role-to-user edit system:serviceaccount:wildwest:default
```
to make app working you have to run commands above with 'wildwest' changed to the project name where frontend is deployed.

I am going to create doc and record demo about how to deploy wildwest game using this extension.

**Comment by dgolovin** [comment]
@carloreggiani FYI: #1531.
