### ISSUE TITLE
selecting the current context from context quickpick shouldn't trigger a context switch

### ISSUE THREAD

**Issue by girishramnani** [redhat-developer/vscode-openshift-tools#1441]
When selecting the same context as the one already set from the context quickpick menu - re-triggered a cluster context switch.
A optimisation opportunity here could be to store the old choice ( context label ) and check if the new one selected by the user is different then only trigger the cluster context switch.

## Plugin Info

Version - `v0.1.4`

**Comment by dgolovin** [comment]
@girishramnani  Actually you should not see current context in quickpick menu at all, because it is filtered out.
Does it make sense to have this switch? Context defines namespace/cluster/user. Switching between contexts that differs only in namespace would have no effect on OpenShift Application Explorer because it always show all available namespaces.

**Comment by dgolovin** [comment]
@girishramnani after looking into it a bit more, I think I found out what is happening here. I think you have contexts with different names but the same cluster and user name. When we switch between contexts like this the OpenShift Application View should not be reloaded.
