### ISSUE TITLE
Support for  s390x and ppc64le binaries for odo and oc

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#1558]
odo and oc binaries are there for s390x and ppc64le architectures. We should include them for our extension build.

**Comment by jeffmaury** [comment]
Where did you get that request from ? My understanding is that this effort is now managed by our org

**Comment by mohitsuman** [comment]
I have added this issue so that we can discuss more on Sprint Planning. I was having a word with Nick Boldt about having support for different archs. But if it is not managed by our org, we might need to update that.

**Comment by jeffmaury** [comment]
Keep it on hold for the moment. I will update the status

**Comment by mohitsuman** [comment]
> Keep it on hold for the moment. I will update the status

okay. Thanks.

**Comment by dgolovin** [comment]
What we should support is IBM's platforms like Z. But those binaries are not going to be included into package published to Vscode marketplace.

**Comment by dgolovin** [comment]
But we should handle not supported platforms and pick up odo and oc form PATH locations.

**Comment by nickboldt** [comment]
Wondering if there's been any movement on this issue re: detecting s90x and ppc64le versions of `oc` and `odo` on `PATH` when not prepackaged into the .vsix file's out/tools/ folder.

**Comment by jeffmaury** [comment]
There is no plan to add the additional binaries to the VSIX files. What we will do in the future is to publish an additional zip files that will contain the odo and oc binaries for the additional platforms that are guaranteed to be in synch with the VSIX file so that you can use it as a stable reference when building your CRW plugin. @nickboldt OK for you ?

**Comment by nickboldt** [comment]
I suppose that would be useful. Today we're just curling from upstream odo and oc sites directly, and using a version that's compatible across all three arches (eg., 4.3.19). So ... version included in the vsix / zip might actually be different (4.3.3?) than the one that we're using due to Brew limitations.

OTOH if you have the version you include in the json file ( https://github.com/redhat-developer/vscode-openshift-tools/blob/master/src/tools.json#L37-L39 ) we could just curl that and use the version you've stated, without more artifact proliferation. 

TBH I'm not sure why you wanted to move from a 9M vsix to a 160M one. Seems like a waste of bandwidth to force mac users to download windows and linux binaries they'll never use.

**Comment by jeffmaury** [comment]
It was done to enhance the developer experience on VSCode. So is a marker properties file containing the version of oc and odo ok for you:
ex content:
```
oc.version=
odo.version=

```

**Comment by nickboldt** [comment]
I'm saying we don't need anything else. 

```
curl -sSL https://github.com/redhat-developer/vscode-openshift-tools/raw/master/src/tools.json -o - | jq ".oc.platform.linux.url" -r | sed -r -e "s#.+/clients/ocp/(.+)/openshift.+#\1#"
4.3.3
```
and

```
curl -sSL https://github.com/redhat-developer/vscode-openshift-tools/raw/master/src/tools.json -o - | jq ".odo.platform.linux.url" -r | sed -r -e "s#.+/clients/odo/v(.+)/odo.+#\1#"
1.2.1
```

No need to do anything else.

**Comment by mohitsuman** [comment]
@nickboldt We will update the tools.json with the specific platform details. PR soon.

**Comment by jeffmaury** [comment]
My understanding is that they will extract the version from the JSON file and then download from upstream/downstream. I would add that we should publish this file next to the VSIX file as @nickboldt example is working from master which may be updated

**Comment by mohitsuman** [comment]
@nickboldt The ppc64 and s390x binaries for `oc` are not listed here 
https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.3.3/ .

**Comment by nickboldt** [comment]
Guys, you don't need to do anything at this point to support z and p.
Binaries already exist on mirror.openshift.
We can read your json to extract the version range you support.
Case closed. :D
