### ISSUE TITLE
Improving plugin name and short description to capture new Kubernetes support

### ISSUE THREAD

**Issue by sspeiche** [redhat-developer/vscode-openshift-tools#1781]
A couple of considerations for improving the ability to discover the plugin and to better make aware the changes with ability to work with Kubernetes clusters, not just OpenShift.

1. The name: "OpenShift Connector". First we'd like to include Kubernetes in the title. Second we'd like to remove the word "Connector", as it doesn't add anything and just makes it longer.
Proposed name: "OpenShift Kubernetes"

2. The short description. It doesn't mention "Kubernetes" support. Also it says it is for VS Code (which is obvious since you are in VS Code marketplace).
Proposed short description: 
    a) Create, quickly iterate on code changes, deploy and debug your OpenShift and Kubernetes applications
    b) End-to-end developer experience for OpenShift and Kubernetes applications

3. The overview. It would be good to mention in the intro paragraph what various cluster types are supported. At least examples, like the Kubernetes plugin has "Works with any Kubernetes anywhere (Azure, Minikube, AWS, GCP and more!)." We should also make it clear we bundle the Kubernetes extension as well.

**Comment by deboer-tim** [comment]
Feedback on #1, when I read that I think it's odd we started clarifying that OpenShift is Kubernetes - i.e. I read it as 'OpenShift is Kube', not 'OpenShift _or_ other Kubes'. There are also several other Kube extensions in the marketplace so might be worth a nod to why this is different, e.g. Kubernetes App Dev.

Steve, are we just trying to be clear that you _could_ use this OpenShift extension for Kube, or trying to appeal to Kube users directly? If the latter, IMHO we should we should downplay or remove OpenShift from the title completely (but keep it clear in the description), and also look at using a different icon.

**Comment by dgolovin** [comment]
> are we just trying to be clear that you could use this OpenShift extension for Kube, or trying to appeal to Kube users directly? 

@deboer-tim, @sspeiche I think it is both 

> are we just trying to be clear that you could use this OpenShift extension for Kube

We are using OpenShift Do (odo) in the extension and most commands you can use from extension translated directly to odo CLI command. Latest release includes odo 2.0.0 and it works with vanilla kubernetes. We need to promote that. 

> trying to appeal to Kube users directly

If you go to Extensions activity in VSCode and search for `kubernetes` OpenShift Connector would be approximately on third page, judging by clicks on the scroll (see animation below). If you look and extensions above Connector you notice they don't always have more installs or more stars. They are all (I am assuming here because I checked only few) have `kubernetes `in name, description and tags. We have `kubernetes` in tags only (see screenshot below).  The idea is to get `kubernetes` in name and description to move our extension up in the search and see if that makes a difference in installs.

![screenshot](https://user-images.githubusercontent.com/620330/95256688-fbdf2380-07d7-11eb-96b6-2fc90485e8e9.png)

![animation](https://user-images.githubusercontent.com/620330/95256372-9428d880-07d7-11eb-9047-a3c4e15c7ea7.gif)

**Comment by serenamarie125** [comment]
Throwing in some ideas for the short description

1. Develop, deploy, and debug applications on Kubernetes or Red Hat OpenShift
1. Develop, deploy, and debug Kubernetes or Red Hat OpenShift applications
1. Streamlined development, deploy, and debug applications on Kubernetes or Red Hat OpenShift
1. Streamlined development experience for Kubernetes or Red Hat OpenShift applications 
1. Streamlined dev experience for Kubernetes or Red Hat OpenShift applications

**Comment by deboer-tim** [comment]
Personal preference for 5, it's unique and still short enough that you should see most in the extension view above. Maybe 'simplified' instead of 'streamlined', or 'app dev' instead of application at the end? i.e.
6. Simplified app dev experience for Kubernetes or Red Hat OpenShift
or just
7. Simplified app dev for Kubernetes or Red Hat OpenShift

**Comment by dgolovin** [comment]
I like variant 7. It is short and gives an idea what exactly to expect from the extension.

**Comment by mohitsuman** [comment]
Keeping `app dev` both as short forms does not justify the whole workflow of the extension. We need to give a broader picture of the functionality of the extension.

I would suggest "Simplified application development with Kubernetes and Red Hat OpenShift". 

@serenamarie125 @deboer-tim what you think ?

**Comment by deboer-tim** [comment]
Yeah, I'm good with that. IMHO we should push these changes, and can always tweak later once we get feedback or see it in context.

**Comment by dgolovin** [comment]
I have already pushed the option 7. Which is good because it is short and will fit well ether in marketplace tiles or in extension list view in vscode.

Honestly I am not following how `app dev` 'does not justify the whole workflow of the extension`, but `application development` does. They are the same words just in short and long forms. Longer form will most likely wont fit in single tile on marketplace site and in vscode Extension List view. 

I am still in favor of short informal option 7.
