### ISSUE TITLE
Clicking on icon to open route fails

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-openshift-tools#1804]
Error running command openshift.url.open: Cannot read property 'status' of undefined. This is likely caused by the extension that contributes openshift.url.open.
<img width="1007" alt="Screen Shot 2020-10-19 at 7 19 10 PM" src="https://user-images.githubusercontent.com/148698/96489769-2ac9b080-1240-11eb-969c-b725f9c96597.png">

see 
* https://youtu.be/_sLr0T7jabg?t=305
* odo issue https://github.com/openshift/odo/issues/4125

**Comment by dgolovin** [comment]
That is happening for quarkus component type because the initial name for url `8080/http` is not valid for deployment and replaced to `8080-http` during deployment. Ext does not expect names are changing after deployment and does not refresh component structure in Application Explorer View.

**Comment by dgolovin** [comment]
using `odo url list -o json` does not help here, because when component gets pushed to cluster url name is changed to 8080-http. The name of url in tree will stay the same and when you click to open it there would be no 8080/http in list. I'll do temp fix by replacing '/' in url name to '-' got avoid this error.
