### ISSUE TITLE
Flow for projects with existing devfile

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-openshift-tools#1815]
When there is an existing devfile, extension requires and component to be created. Component creation fails if there is an existing devfile. With the following. 

`Failed to create Component with error 'Error: Command failed: "/..../redhat.vscode-openshift-connector-0.2.0/out/tools/darwin/odo" create nodejs gatsby-blog  --context /..../my-blog --app my-blog --project gercan-dev
 ✗  accepts between 0 and 1 arg when using existing devfile, received 2`

Extension should skip component creation for projects with existing devfiles.

**Comment by dgolovin** [comment]
@gorkem The problem is `odo` needs `.odo` folder with settings to recognize folder as a component. If we not creating component then it is not going to show up in application explorer. 

```
> ~/p/vscode-openshift-tools/out/tools/linux/odo describe
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```

What we should do instead, we should use that existing devfile.yaml as `odo create --devfile devfile.yaml` and skip component type selection. That should use current devfile and create required `.odo` folder.

```
> ~/p/vscode-openshift-tools/out/tools/linux/odo describe
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```
