### ISSUE TITLE
Add validation for creating a new project starting with forbidden words - ie. openshift

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#1835]

**Comment by dgolovin** [comment]
This is something that cannot be fixed:
1. What is forbidden for OpenShift is fine for k8s
2. There is not way for user get listed all the projects to validate the new project name because of permissions

**Comment by mohitsuman** [comment]
If we can detect the type of cluster, OpenShift or K8s, we can apply the error validation. We need to have the forbidden list (for project names) from odo/console/OpenShift team.

@odockal are you aware of the list for forbidden words ?

**Comment by dgolovin** [comment]
Again, this is something that cannot be fixed, because users w/o administrative privileges have no access to list of the projects. @mohitsuman approach would require implementation to map cluster type/version to prohibited words and maintenance of this map with every new release of OpenShift/K8s.

this is issue in `Won't fix` IMO.

Adequate error message is already there.
