### ISSUE TITLE
Request if components should be deleted when deleting Application or Project from Application explorer

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2023]
As @jrichter1 again pointed out current deletion command behavior for Project or Application is inconsistent. There should be common approach when deleting resources with multiple nested resources in it. There should be confirmation from user requested if all the components within project or application should be deleted as well.

**Comment by datho7561** [comment]
This workflow has changed a bit since this bug was filed (we don't display applications in the application explorer). Is the general idea to update the wording on the prompt to delete a project to include "and all resources in the project"? There isn't a way to delete the project without deleting the resources it contains. Also, there is no obvious way to detect which local components should be deleted when deleting a project, since devfiles don't tie components to a particular project.
