### ISSUE TITLE
Limit the welcome page to a single instance

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#2109]
The welcome page opens up again when the openshift view refreshes, i.e. after creating the first component while logged out.

**Comment by jrichter1** [comment]
Also, it would be nice if the `welcome` command just focused an existing welcome page instead of opening a new one.

**Comment by dgolovin** [comment]
@jrichter1 good catch, welcome command does open existing view, but only if extension was not reactivated. In your case it was when first workspace folder added with component context.

This is upstream vscode issue and I was not able to workaround it. The same issue exists for vscode-quarkus welcome page. 

The problem is happening when vscode is activating extension without deactivating it. This happens when workspace is empty, extension is activated, welcome page created and then new folder added to workspace.
