### ISSUE TITLE
openshift.explorer.refresh command not found

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#216]
Tried to refresh the OpenShift Application Explorer and got this error

Steps to reproduce:
1) Start minishift.CDK
2) In the Clusters explorer, selected the cluster and `Set as current cluster`
3) Switched to the OpenShift Application Explorer and click the `Refresh` button

![image](https://user-images.githubusercontent.com/695993/46874451-7cf9bf00-ce39-11e8-87f2-078f5431b2a7.png)

**Comment by dgolovin** [comment]
That happens because there is declarative part of extension in package.json and actual javascript activation code. Sounds like ether I did something wrong and let let vscode execute commands from extension befor activate method is finished, or activation method is to slow, or bug in vscode. Will be looking into that.

**Comment by dgolovin** [comment]
Looks like k8s extension has the same issue. Marking it as an upstream.

**Comment by dgolovin** [comment]
Cannot be replicated in latest vscode release. Closing.
