### ISSUE TITLE
Create devsandbox setup/login workflow using webview 

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#2236]

**Comment by dgolovin** [comment]
Currently there is no way to do implement it in vscode. Sandbox Rest API works until login into provisioned cluster. RР SSO is disabled. Only token auth can be used to login using CLI tools like oc/odo. To get token user have to open DC in browser then copy login command using user menu in right upper corner. 

JBoss Tools workaround this issue by showing page in browser embedded into modal dialog and then onPage loaded event search for token in resulting page. 

VSCode cannot use this approach, because it runs in browser itself and webview is actually iframe instance. redhat.com pages and openshiftapp.com pages seem prohibit to loading in iframe.
