### ISSUE TITLE
Use GitHub API to get latest odo version

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#239]
The version of odo that is downloaded is hardcoded in the extension. We should use the GitHub API to get the latest version of odo to download and get the download links from there

**Comment by dgolovin** [comment]
We do so, because odo cli options are not stable. If new version of odo released we should test extension against it and then release update to marketplace. Even if odo is already installed and extension can find it in locations configured in PATH env variable, it still have to download hardcoded version of odo if current version is not exactly the same extension supports.
