### ISSUE TITLE
Add UI tests covering command palette offering 

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2483]

**Comment by dgolovin** [comment]
There is no need for testing if commands are in palette through UI, because they are not there only if you have declared it in package.json and then did not registered a handler for it in extension activation method. 

Unit test [here](https://github.com/redhat-developer/vscode-openshift-tools/blob/d6f7b8ece5cf7409b75f223d4b19a977f4e218a8/test/unit/extension.test.ts#L109) covers those kind of errors.
