### ISSUE TITLE
Cannot Start Dev action on quarkus component until an OpenShift Project is created

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2581]
Env. Linux, Fedora 36, OCP: local CRC 2.9.0.

1. Connect to the cluster (crc)
2. Create a quarkus component
3. Run start Dev on the component
4. Assert: Component is being "pushed" to the cluster
Actual result: Nothing happens, just Starting odo dev put to console. After the project is created this works.

Maybe it is simply not that clear to me, but I could not execute (it does nothing, just wrote out Starting odo dev but nothing else) Start Dev operation on created quarkus component, until a project is created on OpenShift connection.

**Comment by dgolovin** [comment]
@odockal It now works differently and reports the problem. The error message does not mention missing project, but at least the terminal output is not totally empty. See screenshot below.
@mohitsuman it can be improved by checking if project exists before running the 'odo dev'. Not blocking v1.0.0 IMO.

**Comment by odockal** [comment]
@dgolovin Much better with error reported. I would consider this use case to be corner one, not blocking anything.

**Comment by mohitsuman** [comment]
I am moving this to next milestone.

**Comment by mohitsuman** [comment]
@datho7561 can you please verify if this error still persists with the latest release. And if we can add any resolution to it if needed.

**Comment by datho7561** [comment]
I don't know how to trigger the 'Create new or set project' tree item anymore. Even when I manually modify my `~/.kube/config`  to not have a namespace, OpenShift Toolkit picks up `default` as the current namespace.

**Comment by datho7561** [comment]
I reproduced the project not being set. Not sure what I did to get to that state though.

**Comment by mohitsuman** [comment]
@datho7561 is this still an issue with latest release ?

**Comment by datho7561** [comment]
Yes, this is still an issue. Here is how to reproduce it:
1. Modify your `~/.kube/config` so that the current context points to a namespace that doesn't exist on the cluster you are working on
2. Open vscode-openshift-toolkit and verify that the "project" item in the application explorer has a warning symbol and the description "Missing Project. Create new or set active Project"
3. Right click on a component in the "Components" sidebar section and click "Start Dev"
4. The OpenShift terminal should appear. There will be text that says "Error occured on push" in the output. The component is erroneously listed as running in the "Components" section of the sidebar.

In order to fix it, we should check if the current project exists before running `odo dev`. Maybe we should show an error popup, or maybe we should display a prompt to select a project.
