### ISSUE TITLE
Logging out of the cluster (crc) throws an error notification: All promises were rejected

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-openshift-tools#2604]
Logging out of the cluster show this error notification. Besides that, when I log out, there is stil active option on Os connection to "change active project", which should not be present imho. If I click on it while logged out, it throws:
```
Cannot retrieve projects for current cluster. Error: Error: Command failed: "/home/odockal/.vscode/extensions/redhat.vscode-openshift-connector-0.7.2/out/tools/linux/oc" get project -o=json Error from server (Forbidden): projects.project.openshift.io is forbidden: User "system:anonymous" cannot list resource "projects" in API group "project.openshift.io" at the cluster scope
```

and again All promises were rejected.

**Comment by odockal** [comment]
It seems that I am not really logged out. That will be the problem.

**Comment by dgolovin** [comment]
@odockal to support OpenShift and Kubernetes clusters we cannot use ```oc whoami``` because that would not work for Kubernetes cluster provisioned with Docker desktop or minikube or any other tool.

So we use  ```odo version``` and look for server url in output. Apparently something changed and now odo prints out api url even if not user is  logged in.

**Comment by odockal** [comment]
@dgolovin works fine!
