### ISSUE TITLE
When connected to DevSandbox, "OpenShift: Start Dev" results in error 

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#2792]
1. Use `odo` to create the starter code and `devfile.yaml` for a Go component
2. Connect to a DevSandbox instance
3. Run "OpenShift: Start Dev"

Expected: component is pushed to the cluster and run in dev mode
Actual: an error popup appears that says:

`Cannot read properties of undefined (reading 'contextPath')`

**Comment by datho7561** [comment]
It seems like some of the commands are decorated with "@selectTargetComponent". If I add this to the `dev` function in `components.ts`, instead I get a popup with the following error:

`You need at least one Project available. Please create new OpenShift Project and try again.`

However, I have a project created, and I can only have one project due to the limitations of DevSandbox.

**Comment by datho7561** [comment]
When I do `oc get project -o json`, the result is the following:

```json
// ...
    "items": [
        {
            "apiVersion": "project.openshift.io/v1",
            "kind": "Project",
            // ...
           "status": {
                "phase": "Active"
            }
        }
// ...
```

The method used to list the projects on the current cluster uses this command, and tries to read the property `project.status.active` (`odo.ts#499`) in order to determine if the project is active. Since that property doesn't exist, vscode-openshift-toolkit believes all projects are inactive. So when it goes to deploy a component, it cannot locate the active project, and concludes there are no projects on the cluster.

**Comment by dgolovin** [comment]
@datho7561 thank you for reporting this and providing a PR. The problem is that this command is not supposed to be available form palette, because it is is not letting you to select targeted component. So the simplest way to fix it to hide it form palette (1)

Then you will face real issue. The extension is not identifying current project correctly when you provision sanbox and login to it first time (2).

If you fix (2), you should be able to fix (1) by just using the selectTargetComponent annotation for dev method.

**Comment by datho7561** [comment]
Okay. I'm going to close the draft PR I have. Should I make a PR to hide the commands that only work from the component right click menu? I don't know how complex identifying the current project when connecting to a cluster is, but it would be nice to prevent users from using the command from the palette if it doesn't work.
