### ISSUE TITLE
`Open in Browser` does not work when cluster has more than one project

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/vscode-openshift-tools#293]
The `Open in Browser` command tries  to load a route based on the component name but does not use the application and the project in the filter

**Comment by dgolovin** [comment]
Component name is generated as ${component-name}-${app-name}. With the name including app name there is no need to filter by application.  It seems problem is definitely in missing --namespace option, because in case there are more than one project all `oc` commands without --namespace apply to the active project which is not necessarily match one for component targeted in 'OpenShift Application Explorer' tree.
