### ISSUE TITLE
No Login possible since 1.3.0

### ISSUE THREAD

**Issue by Headley-76** [redhat-developer/vscode-openshift-tools#3027]
Hi all,

since version 1.3.0 I can't login to our intranet cluster. I get the message like ("not reachable...is the server running an up").

Version 1.2.0 is working fine. Version 1.30, 1.4.0 and 1.5.0 got the error. 

Can someone check that?

Greetings from germany
Headley

**Comment by datho7561** [comment]
In https://github.com/redhat-developer/vscode-openshift-tools/commit/f3d18b5fc5619a5df7a5956c0eaa5929044c86d2 I added a check to see if the cluster is up before attempting to login. In order to check if the cluster is accessible, the extension sends a GET request to `$CLUSTER_URL/api` (eg. `https://api.crc.testing:6443/api` in the case of OpenShift Local). Even if you are logged out of the cluster, the cluster should give a response to this request, likely a 403 FORBIDDEN since you don't have permissions to access the api when you aren't logged in.

If you send a GET request to the api from the command line when you are logged out of the cluster, does it give a 403? eg.
- `curl $CLUSTER_URL/api` on Linux and macOS
- `Invoke-WebRequest $CLUSTER_URL/api` on Powershell on Windows
(replace $CLUSTER_URL with the actual URL of the cluster you are trying to connect to)

If you get something other than a 403 FORBIDDEN, please let me know, as we might have to find a different method to check if the cluster is running.

**Comment by Headley-76** [comment]
Hi @datho7561 ,

I send a GET request to https://my-cluster/api. In the browser I got the correct http 403. But the curl with PowerShell got http 502.

HTTP/1.0 200 Connection established

HTTP/1.1 502 cannotconnect
Connection: Keep-Alive
Content-Type: text/html
Cache-Control: no-cache
Content-Length: 2421
X-Frame-Options: deny

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>


<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

It seems, that are some company proxy rules, who differs from browser and shell. 

But HTTPS_PROXY and NO_PROXY environment variables are set. I don't have any idea.... :-(

**Comment by Headley-76** [comment]
After another try and error, I disabled the proxy for my internal domain, the request was successful (304) with POSTMAN. But I the windows environment NO_PROXY is set but not working. How can I fix, to disable the proxy for my domain in windows? Or can I set this option in VS Code separately?

**Comment by Headley-76** [comment]
Problem fixed. The NO_PROXY environment variable was not set correctly. 
It should be: .my-company.com,localhost
and not: *.my-company.com, localhost
