### ISSUE TITLE
No proper logs showing in new OpenShift terminal  when running odo dev

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-openshift-tools#3031]
When I am trying to run `odo dev` on my local, the new OpenShift terminal was opened but there were no proper logs in it.
![error-openShift-terminal](https://github.com/redhat-developer/vscode-openshift-tools/assets/93245779/f4720aa2-e146-48b2-ba9f-76358a045637)

Running on the below OS:

> Edition	Windows 11 Enterprise
> Version	22H2
> Installed on	‎3/‎23/‎2023
> OS build	22621.1992
> Experience	Windows Feature Experience Pack 1000.22644.1000.0

**Comment by datho7561** [comment]
I think the root cause is https://github.com/microsoft/node-pty/issues/138, let me investigate a bit more...

**Comment by datho7561** [comment]
I spent at least half of the day yesterday trying to figure out why this isn't working on Windows, and I didn't get much further. The only lead that I have is that `nodePty.spawn()` blocks on Windows. By that, I mean it never returns and doesn't throw an error, and since it's not an asynchronous call, I can't create a timeout for it. I've verified that I am passing the correct absolute path to `odo.exe`. I've also tried calling `nodePty.spawn()` with `cmd.exe`, but that also freezes the process. I will need to dig around another codebase that uses `node-pty`, such as VS Code or Hyper.js, to figure out if they do anything different when spawning the process on Windows.
