### ISSUE TITLE
Create Component from Folder doesn't trim suggested name to last portion of the path on Windows

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3127]
To reproduce:
- Use Windows
- Open a project without a devfile as a workspace (eg. run the "Add folder to workspace" command, then select a sample project without a devfile)
- Right click on the folder, and select "Create Component from Folder"

*expected*: the "component name" field is populated with the folder name

*actual*: the "component name" is populated with the absolute path of the folder, using a Windows-style path (with drive letter and `\`)

**Comment by rgrunber** [comment]
Speaking of component name, could we try to sanitize the initial component name for git repo imports :

https://github.com/redhat-developer/vscode-openshift-tools/blob/843dca55f82b6c408d4f518f98c18c81236826cb/src/webview/create-component/pages/fromExistingGitRepo.tsx#L415

so that they respect https://github.com/redhat-developer/vscode-openshift-tools/blob/843dca55f82b6c408d4f518f98c18c81236826cb/src/webview/common-ext/createComponentHelpers.ts#L95-L99 . Can be included in a separate PR.

(eg. https://github.com/openshift-evangelists/Wild-West-Frontend fails validation )
