### ISSUE TITLE
Improve progress monitor when creating a new component, currently blocked on 70% for several seconds/minutes

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#368]
it goes directly on 70% and stays blocked on it for several seconds/minutes
![image](https://user-images.githubusercontent.com/1105127/48776561-7e3bc880-ecd0-11e8-9f6c-e1afbda3a8e1.png)

**Comment by jeffmaury** [comment]
Time to pull images ?

**Comment by apupier** [comment]
> Time to pull images ?

Where to look to know?

I noticed that in Ouput -> OpenShift, it stays on

```
"C:\Users\Aurelien Pupier\.vs-openshift\odo.exe" push --local c:\ws\workingDirectoryForTest\fuse-rest-http-booster
Pushing changes to component: rest-http-booster
Please wait, building component....
```

and when the notification is removed a the full build information is logged, finsishing with

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:52 min
[INFO] Finished at: 2018-11-20T15:50:18Z
[INFO] Final Memory: 55M/97M
[INFO] ------------------------------------------------------------------------
Copying Maven artifacts from /tmp/src/target to /deployments ...
Running: cp *.jar /deployments
... done
+ /var/lib/supervisord/bin/supervisord ctl stop run
run: stopped
+ /var/lib/supervisord/bin/supervisord ctl start run
run: started
changes successfully pushed to component: http-booster
```

**Comment by jeffmaury** [comment]
If it finished then I would say it's ok that's just that the build is long to create (pull images) and execute

**Comment by apupier** [comment]
i think the user experience needs to be improved. I really thought that it was frozen the first time.

different possibilities:
- provide a progress monitor which is more precise (connecting to the deployment pod?)
- provide information where to look in the OpenShift instance
- log in output -> OpenShift continuously (even if in case there are several things to log in parallel it might be complicated to understand) and points to it
- provide a link open the pod log in a specific view in VS Code

**Comment by dgolovin** [comment]
> i think the user experience needs to be improved. I really thought that it was frozen the first time.

I agree, we can make improvements here, but keep in mind VSCode API is extremely limited and it is not always possible to do what we want.

> 
> different possibilities:
> 
> * provide a progress monitor which is more precise (connecting to the deployment pod?)

It is impossible to do precise reporting on progress, especially when we are talking about different languages and build tools. It might be better if we show 'undefined progress bar', just to show it is in progress and avoid confusion from wrong progress reporting. 
Also running component creating commands in terminal instance might be better that current implementation, because it would have continuous output you mentioned below.

> * provide information where to look in the OpenShift instance

We can provide a command that would open OpenShift Console focused on created component (Deployment Config). Is that what you have in mind?

> * log in output -> OpenShift continuously (even if in case there are several things to log in parallel it might be complicated to understand) and points to it

I tried that and It did not work, it is not complicated it is just way too messy. You can try it by running different commands at the same time and refreshing OpenShift Application Explorer. 

> * provide a link open the pod log in a specific view in VS Code

Currently we use dedicated terminal view, what is missing is proper and unique name for terminal so i can be found and can be reused for command execution.

**Comment by dgolovin** [comment]
Now undetermined progress bar is shown for all long running operations. Further improvements will be done as part of #717.
