### ISSUE TITLE
Display status information for Deployments in Application Explorer tree

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-openshift-tools#3823]
It would be nice to report status information for deployments. For example, we can include:
- The number of available replicas
- The number of configured replicas
- If the Deployment is in CrashLoopBackoff
- Some way to indicate any other errors the Deployment has run into

For the last two, maybe we could do some sort of warning/error icon, with hover text that gives the specific error message.

**Comment by vrubezhny** [comment]
As an example of a "Successful" deployment:

![Screenshot from 2024-05-22 02-50-31](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/645af555-f3ef-4a67-9f7c-473b3b6ebfb5)

...and a "Failing" deployment:
![Screenshot from 2024-05-22 02-57-18](https://github.com/redhat-developer/vscode-openshift-tools/assets/620781/5dfe9c93-258d-4728-ae2e-1c00c5fe9fdd)

Not sure if I correctly get on how can I detect a "Failed" deployment, as I'm not sure if Pods statuses are really replicated to the according Deployment's `element.status.conditions` array... A Deployment `conditions` array looks more like a log of events, like:
```
  conditions: [
    {
      lastTransitionTime: "2024-05-16T18:42:14Z",
      lastUpdateTime: "2024-05-16T18:42:14Z",
      message: "Deployment has minimum availability.",
      reason: "MinimumReplicasAvailable",
      status: "True",
      type: "Available",
    },
    {
      lastTransitionTime: "2024-05-16T18:41:59Z",
      lastUpdateTime: "2024-05-16T18:42:14Z",
      message: "ReplicaSet \"my-deployment-6b7d4f4794\" has successfully progressed.",
      reason: "NewReplicaSetAvailable",
      status: "True",
      type: "Progressing",
    },
  ],
```

`CrashLoopBackOff` status is surely can be find as a Pod status - so we probably should enumerate the available Pods statuses in order to detect its presence, shouldn't we?

@datho7561 WDYT?

**Comment by datho7561** [comment]
I think you might need to list the pods in order to collect this information.
