### ISSUE TITLE
Developer Sandbox Login experience enhancement

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-openshift-tools#3838]
Improve the developer sandbox login experience using Builder service account.

**Comment by datho7561** [comment]
Here's what I've figured out so far:
1. OpenShift Sandbox has a `builder` service account, but by default the account doesn't have enough permissions to do anything useful on the cluster. There is a role called `edit` that the user account. If we use a role binding to assign the `builder` account this role, then it can be used for vscode-openshift
2. The service account `pipeline` already has the `edit` role, so we can try using that account instead of `builder`
