### ISSUE TITLE
No terminals opened

### ISSUE THREAD

**Issue by LoveraSantiago** [redhat-developer/vscode-openshift-tools#3898]
After added and connect to a OC Cluster, when openning the OPENSHIFT TERMINAL it displays No terminals opened with a red reload icon.

![image](https://github.com/redhat-developer/vscode-openshift-tools/assets/7741737/f9338417-7933-4b93-a624-4a9afb78eacc)

What I can do?
Thanks.

**Comment by datho7561** [comment]
If you don't mind me asking, what are you expecting to be there? I think we can improve the name or do a better job of explaining what it's meant for in the UI.

The OpenShift Terminal section is used for running interactive command line programs that interact with the cluster. For example, if you create a component and start debugging it, the terminal command that runs the debug session will be shown here so that you can watch the logs. Another example is building and running a Knative serverless function.

**Comment by LoveraSantiago** [comment]
thank you for your attention.

I was believing it was a terminal to run oc commands.
Example oc help.
I didn't know it was for use after connecting to a component.
Sorry

**Comment by datho7561** [comment]
It's all good. This just means we should indicate this more clearly in the UI.

**Comment by datho7561** [comment]
I think we should add a subtitle below "No terminals opened" that says:

"Terminals related to operations performed on the OpenShift cluster will appear here"
