### ISSUE TITLE
Migrate Kubernetes extension commands

### ISSUE THREAD

**Issue by msivasubramaniaan** [redhat-developer/vscode-openshift-tools#3990]
Replace extension.vsKubernetesLoad, extension.vsKubernetesUseNamespace command functionality

Ref: https://github.com/redhat-developer/vscode-openshift-tools/issues/3981

**Comment by vrubezhny** [comment]
It doesn't look that we really need anything to do with `extension.vsKubernetesUseNamespace` - we use `openshift.project.set` to set/change active namespace/project from Command Palette/Status Bar/Context menu. 
I believe we can just remove any `extension.vsKubernetesUseNamespace` registrations/references as not used.

**Comment by vrubezhny** [comment]
For the `extension.vsKubernetesLoad` command we've already have a replacement: `openshift.resource.load`. The only problem here is that when we remove the k8s extension dependency then we get rid of `KubernetesResourceVirtualFileSystemProvider` virtual file system provider that, as far as I understand, is registered by the k8s extension to respond to URI requests to load deployment/pod/etc. yaml-files like  `k8smsx(ro)?://loadkubernetescore/`, `k8smsx(ro)?://kubernetesdescribe/`, `k8smsx(ro)?://helmget/` - so we have to add this virtual file system provider to vscode openshift tools in order to make it working correctly without having the k8s extension installed.
However some other modifications/fixes might be also required, f.i., [Implement Port Forward IU (add/remove/show related information) #3906](https://github.com/redhat-developer/vscode-openshift-tools/issues/3906)
