### ISSUE TITLE
.NET not supported well; newest devfile is .NET 5; current .NET is 9

### ISSUE THREAD

**Issue by DonSchenck** [redhat-developer/vscode-openshift-tools#4108]
When suggesting a devfile for my .NET project, the newest version shown is .NET 5. This is several years old and out of date.

**Comment by datho7561** [comment]
This isn't good; there are a few parts that are broken:
- There is a .NET 6 Devfile in the default Devfile registry, and this should be suggested over .NET 5, given that .NET 5 is EOL (from what I understand). This will probably need to be addressed in https://github.com/devfile/alizer
- We should create Devfiles for more recent versions of .NET in the default Devfile registry

Also, when I run a RHEL 9.4 ubi image using `toolbox`, only dotnet 6, 7, and 8 are available for install using `dnf`. This might complicate setting up a .NET 9 Devfile, since the Devfiles make use of RHEL UBI container images.

**Comment by mohitsuman** [comment]
@msivasubramaniaan can you please work with @datho7561 and get this updated in the devfile registry and we can accordingly move this for `1.15.0` release or the next release.

**Comment by mohitsuman** [comment]
Registry is available at https://registry.devfile.io/viewer/devfiles/community/dotnet80. @msivasubramaniaan can we close this issue ?

**Comment by msivasubramaniaan** [comment]
Yes Closing this issue.
