### ISSUE TITLE
Devfile Registry header were lost fixing #4536

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-openshift-tools#4587]
follows up on #4536 

Fixing #4536 made Devfile Registry header disappear. See https://github.com/redhat-developer/vscode-openshift-tools/pull/4536#issuecomment-2441415304

**Comment by vrubezhny** [comment]
@adietish The header isn't actually lost. It's removed from all our views for creating a project from template and a helm chart in order to make these views to be more compact:

![Image](https://github.com/user-attachments/assets/d1b7131d-1e8f-45bf-a4a3-3c201b0c2c02)

Previously, the headers were "eating" too much space not allowing to display more than 2-3 items on the search page depending on VSCode scale preference, see for example:

![Image](https://github.com/user-attachments/assets/2e9d4d74-1773-4d5e-81f2-c44f86426856)

At the same time the header text is available on view title, so duplicating it on the view's page space doesn't look needed.

So, closing this as WON'T FIX. Feel free to reopen if needed.
