### ISSUE TITLE
No element under openshift application explorer view excpet the namespace

### ISSUE THREAD

**Issue by dharmjit** [redhat-developer/vscode-openshift-tools#790]
Hi Team,

After the successful login into cluster, I am not seeing anything under the cluster/namespace. But in my cluster I have created many objects.

odo version
odo v0.0.20 (bd3e74a4)

openshift connector
0.0.19

Thanks,

**Comment by jeffmaury** [comment]
The Application Explorer does not expose all Kubernetes resources but only `odo` compliant ones. We are working with Microsoft so that the VSCode Kubernetes extension can be used against OpenShift clusters

**Comment by dgolovin** [comment]
@dharmjit, @jeffmaury answer is correct. 

You can use [k8s extension from Microsoft](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) and [CloudCode from Google](https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode) to browse k8s resources, but be ready for some limitations:
* OpenShift specific resources like projects and routes not being available in tree
* Some resources cannot be seen due to more strict access rules for OpenShift clusters

**Comment by dharmjit** [comment]
@jeffmaury @dgolovin, are you suggesting that I should not use this plugin. And are the deploymentsconfigs, services, routes not odo complaint? Can it be the case of access priveleges to my oc account?

**Comment by jeffmaury** [comment]
No the extension was designed to hide K8S complexity so it does not discover what's in your cluster but only what was previously created by itself. This kind of expert mode is in the roadmap

**Comment by dgolovin** [comment]
Duplicated by #1668.

**Comment by dgolovin** [comment]
Duplicated by #80.
